version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-mysecretpassword}@127.0.0.1:5432/blog_db?schema=public
    container_name: blog-nextjs
    restart: always
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-mysecretpassword}@db:5432/blog_db?schema=public
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-here-generate-with-openssl-rand-base64-32}
      - AUTH_TRUST_HOST=true
      # Add other environment variables as needed or use an env_file
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads
    # If you want to use a separate .env file for the container
    # env_file:
    #   - .env.production

volumes:
  pgdata:
