-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Software" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "shortDesc" TEXT NOT NULL,
    "websiteUrl" TEXT,
    "logoUrl" TEXT,
    "pricing" TEXT NOT NULL DEFAULT 'Free',
    "platforms" TEXT,
    "licenseType" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "sourceUrl" TEXT,
    "lastCrawledAt" DATETIME,
    "isAi" BOOLEAN NOT NULL DEFAULT false,
    "categoryId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Software_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "SoftwareCategory" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_Software" ("categoryId", "createdAt", "description", "id", "isAutoGenerated", "lastCrawledAt", "licenseType", "logoUrl", "name", "platforms", "pricing", "shortDesc", "slug", "sourceUrl", "updatedAt", "websiteUrl") SELECT "categoryId", "createdAt", "description", "id", "isAutoGenerated", "lastCrawledAt", "licenseType", "logoUrl", "name", "platforms", "pricing", "shortDesc", "slug", "sourceUrl", "updatedAt", "websiteUrl" FROM "Software";
DROP TABLE "Software";
ALTER TABLE "new_Software" RENAME TO "Software";
CREATE UNIQUE INDEX "Software_slug_key" ON "Software"("slug");
CREATE INDEX "Software_categoryId_idx" ON "Software"("categoryId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
