const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const count = await prisma.software.deleteMany({ where: { isAutoGenerated: true } });
  console.log(`Deleted ${count.count} programs.`);
}
main().finally(() => prisma.$disconnect());
